// Code generated by goctl. DO NOT EDIT.
package types

type CreateTaskReq struct {
	CreateTaskTaskItem
}

type CreateTaskResp struct {
	TaskItemResp
}

type TaskItemReq struct {
	TaskName string `path:"task_name"`
}

type CreateTaskTaskItem struct {
	BelongToService string `json:"belong_to_service"`
	CronSpec        string `json:"cron_spec"`
	TaskType        string `json:"task_type"`
	TaskName        string `json:"task_name"`
	TaskRemark      string `json:"task_remark"`
	Target          string `json:"target"`
	State           int `json:"state"`
}

type TaskItemResp struct {
	CreateTaskTaskItem
	UpdatedAt string `json:"updated_at"`
}

type TasksCollectionReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=10"`
}

type TasksCollectionResp struct {
	TaskItemResp
}

type SwitchTaskStateReq struct {
	TaskName string `path:"task_name" validate:"required"`
	State    string `json:"state" validate:"required,eq=1|0"`
}

type SwitchTaskStateResp struct {
	TaskName string `json:"task_name"`
}
