// Code generated by goctl. DO NOT EDIT.
// Source: mqueue.proto

package server

import (
	"context"

	"mqueue/cmd/rpc/internal/logic"
	"mqueue/cmd/rpc/internal/svc"
	"mqueue/cmd/pb/task"
)

type TaskServer struct {
	svcCtx *svc.ServiceContext
	task.UnimplementedTaskServer
}

func NewTaskServer(svcCtx *svc.ServiceContext) *TaskServer {
	return &TaskServer{
		svcCtx: svcCtx,
	}
}

func (s *TaskServer) CreateWorkOrder(ctx context.Context, in *task.WorkOrderReq) (*task.WorkOrderReply, error) {
	l := logic.NewCreateWorkOrderLogic(ctx, s.svcCtx)
	return l.CreateWorkOrder(in)
}
